# ============================================================================== 
# MaehrDocs - Zentrale Konfigurationsdatei
# ------------------------------------------------------------------------------
# Diese Datei definiert alle relevanten Einstellungen für das automatisierte 
# Dokumentenmanagementsystem MaehrDocs.
#
# Enthalten sind:
# - Verzeichnisstrukturen für Eingabe, Ausgabe, Papierkorb und Protokolle
# - OpenAI API-Parameter für die KI-gestützte Dokumentenanalyse
# - Einstellungen zur Dateigröße, Seitenzahl, OCR und Duplikaterkennung
# - Formatvorgaben für Dateinamen
# - GUI-Designoptionen wie Theme, Farben, Benachrichtigungen und Fenstergröße
# - Logging-Verhalten für Datei- und Konsolenausgabe
# - Automatisierungsregeln inkl. Zeitplänen und Benachrichtigungen
# - Erweiterte Debug-, Performance- und Sicherheitseinstellungen
#
# Hinweise:
# - Alle Pfade können individuell angepasst werden
# - Änderungen an dieser Datei wirken sich direkt auf das Verhalten der Anwendung aus
# - Kommentare und Formatierung beibehalten, um Übersicht und Lesbarkeit zu gewährleisten
# ============================================================================== 


# Pfade zu den Verzeichnissen
paths:
  input_dir: "C:\\Users\\renem\\OneDrive\\09_AutoDocs\\01_InboxDocs"
  output_dir: "C:\\Users\\renem\\OneDrive\\09_AutoDocs\\02_FinalDocs"
  trash_dir: "C:\\Users\\renem\\OneDrive\\09_AutoDocs\\03_TrashDocs"
  processed_dir: "C:\\Users\\renem\\OneDrive\\09_AutoDocs\\04_Archived_InboxDocs"
  business_docs_dir: "C:\\Users\\renem\\OneDrive\\09_AutoDocs\\05_BusinessDocs"
  excel_dir: "C:\\Users\\renem\\OneDrive\\09_AutoDocs\\06_ExcelDocs"
  payments_dir: "C:\\Users\\renem\\OneDrive\\09_AutoDocs\\07_Payments_ReconciliationDocs"
  backup_dir: "C:\\Users\\renem\\OneDrive\\09_AutoDocs\\08_BackupDocs"
  log_dir: "C:\\Users\\renem\\OneDrive\\09_AutoDocs\\09_LogDocs"

# OpenAI API-Einstellungen
openai:
  model: "gpt-4o"  # Leistungsstärkeres Modell für präzisere Dokumentenanalyse
  temperature: 0.2  # Niedrige Temperatur für höhere Präzision
  max_retries: 5  # Erhöhte Anzahl der Wiederholungsversuche bei API-Fehlern
  api_key_env: "OPENAI_API_KEY"  # Name der Umgebungsvariable für den API-Schlüssel
  system_prompt: "Du bist ein Experte für automatisierte Dokumentenverarbeitung mit Schwerpunkt auf deutschsprachigen Geschäftsdokumenten. Deine Aufgabe ist es, folgende Informationen präzise zu extrahieren und im JSON-Format zurückzugeben:\n1. absender: Identifiziere den genauen Firmennamen/Behörde/Person inkl. Rechtsform.\n2. datum: Erkenne das relevanteste Datum (Rechnungsdatum, Vertragsdatum, Briefdatum) im Format YYYY-MM-DD.\n3. dokumenttyp: Kategorisiere das Dokument eindeutig in eine der vorgegebenen Typen.\n4. betreff: Extrahiere den Kern-Betreff oder Hauptzweck des Dokuments in maximal 10 Wörtern.\n5. kennzahlen: Erfasse wichtige numerische Werte wie Rechnungsnummer, Kundennummer, Betrag (mit Währung), Steuerbeträge.\n\nBeachte typische Strukturelemente wie Briefkopf, Betreffzeile, Anrede, formelle Schlussformeln. Bei Unklarheiten wähle die präziseste mögliche Kategorisierung und gib Sicherheitsstufen in Prozent an."

# Dokumentverarbeitungseinstellungen
document_processing:
  max_file_size_mb: 25  # Maximale Dateigröße in MB
  similarity_threshold: 0.85  # Schwellenwert für Duplikaterkennung (0.0 - 1.0)
  max_pages_to_analyze: 25  # Maximale Anzahl zu analysierender Seiten bei großen Dokumenten
  extract_images: true  # Bilder aus PDFs extrahieren für bessere Analyse
  ocr_enabled: true  # OCR für Dokumente ohne extrahierbaren Text aktivieren

# Regeln zur automatischen Generierung sauberer Dateinamen
filename_rules:
  capitalize_doc_type: true             # Dokumenttyp in Großbuchstaben
  remove_type_from_subject: true        # „Rechnung“ o. ä. aus Betreff entfernen
  abbreviate_subject: true              # Längere Begriffe wie „Arbeitsmedizinische Betreuung 4. Quartal 2023“ → „AMB-4Q23“
  shorten_sender_names: true            # Lange Absender vereinfachen (z. B. mit Mapping)
  replace_spaces_with: "_"              # Trennzeichen im Dateinamen
  max_filename_length: 100              # Maximale Zeichenlänge für Dateinamen
  normalize_umlauts: true               # Umlaute umwandeln (z. B. „ü“ → „ue“)
  clean_special_chars: true             # Sonderzeichen entfernen (z. B. \", *, ?, etc.)

  # Erweiterte Liste gültiger Dokumenttypen
  valid_doc_types:
    - Abrechnung
    - Analyse
    - Angebot
    - Anleitung
    - Antrag
    - Arbeitsvertrag
    - Beleg
    - Bericht
    - Bescheid
    - Bestellung
    - Bestätigung
    - Bewerbung
    - Brief
    - Broschüre
    - Diagramm
    - Dokument
    - Einwilligungserklärung
    - Einladung
    - Entgeltabrechnung
    - Exposé
    - Fahrplan
    - Flyer
    - Formular
    - Garantiebeleg
    - Gutschrift
    - Handbuch
    - Konzept
    - Kontoauszug
    - Kostenvoranschlag
    - Kündigung
    - Kündigungsbestätigung
    - Lebenslauf
    - Lieferschein
    - Lizenz
    - Mahnung
    - Manuskript
    - Meldung
    - Mietvertrag
    - Mitgliedsausweis
    - Newsletter
    - Organigramm
    - Patientenverfügung
    - Plan
    - Präsentation
    - Pressemitteilung
    - Protokoll
    - Prüfbericht
    - Rechnung
    - Richtlinie
    - Schulungsunterlagen
    - Spezifikation
    - Steuerbescheid
    - Steuernachweis
    - Studie
    - Teilnahmebescheinigung
    - Ticket
    - Urkunde
    - Vertrag
    - Vergleich
    - Versicherungspolice
    - Verschwiegenheitserklärung
    - Vollmacht
    - Zertifikat
    - Zeugnisdokument
    - Übersicht

  # Format für Dateinamen nach der Verarbeitung
  filename_format: "{datum}_{typ}_{absender}_{betreff}.pdf"
  date_format: "%Y-%m-%d"  # YYYY-MM-DD Format für Datum im Dateinamen
  processed_file_prefix: "PROCESSED_{date}_"  # Präfix für verarbeitete Dateien mit Datum

# Verarbeitungspipeline
processing_pipeline:
  perform_ocr_first: true  # OCR vor Textextraktion durchführen
  extract_tables: true  # Tabellen als strukturierte Daten extrahieren
  extract_metadata: true  # PDF-Metadaten für die Analyse berücksichtigen
  use_keywords_list: true  # Keyword-basierte Vorfilterung nutzen

# Erweiterte Duplikaterkennung
duplicate_detection:
  enabled: true  # Duplikaterkennung aktivieren
  hash_compare: true  # Hash-basierter Vergleich für schnelle Erkennung exakter Duplikate
  content_compare: true  # Inhaltsvergleich für ähnliche Dokumente
  check_in_output_dir: true  # Auch im Ausgabeordner nach Duplikaten suchen
  check_in_processed_dir: true  # Auch im Ordner für verarbeitete Dokumente nach Duplikaten suchen
  generate_report: true  # Duplikatbericht generieren
  report_format: "html"  # Format des Duplikatberichts (text, json, html)
  visual_comparison: true  # Visuellen Vergleich für gefundene Duplikate erstellen

# Dateiversionsmanagement
version_control:
  enabled: true  # Änderungshistorie für Dokumente führen
  max_versions: 3  # Maximale Anzahl alter Versionen
  compare_versions: true  # Unterschiede zwischen Versionen anzeigen

# Datenschutzeinstellungen
privacy:
  redact_sensitive_data: true  # Sensible Daten wie IBAN/Personalausweisnummer schwärzen
  compliance_mode: "DSGVO"  # Datenschutzstandards einhalten
  encryption_enabled: false  # Vertrauliche Dokumente verschlüsseln

# KI-Performance-Optimierung
ai_optimization:
  context_window: 8000  # Maximale Textlänge für die API
  batch_processing: true  # Dokumentenstapel gemeinsam analysieren
  confidence_threshold: 0.75  # Mindestvertrauen für Extraktionen
  retry_with_different_model: true  # Bei niedrigem Vertrauen präziseres Modell nutzen

# GUI-Einstellungen
gui:
  theme: "dark"  # Farbschema (dark, light)
  window_size: "1700x1300"  # Fenstergröße
  font_size: 12  # Schriftgröße
  show_duplicate_popup: true  # Popup anzeigen, wenn Duplikat gefunden wird
  notify_on_completion: true  # Benachrichtigung anzeigen, wenn Verarbeitung abgeschlossen ist
  enable_sounds: false  # Soundeffekte aktivieren
  check_interval_seconds: 5  # Intervall für die Überprüfung auf neue Dokumente
  notify_on_new_documents: true  # Benachrichtigung anzeigen, wenn neue Dokumente gefunden werden

  # Anpassbare Farben
  colors:
    background_dark: "#0D1117"    # Tiefdunkles Blau-Schwarz
    background_medium: "#161B22"  # Etwas hellerer Hintergrund
    card_background: "#1F2937"    # Dunkles Grau-Blau für Panels
    primary: "#3B82F6"            # Auffälliges, modernes Blau
    accent: "#60A5FA"             # Helleres Blau für Hover
    text_primary: "#F9FAFB"       # Fast weiß
    text_secondary: "#9CA3AF"     # Mittelhelles Grau-Blau
    success: "#10B981"            # Frisches Grün
    warning: "#FBBF24"            # Sattes Gelb-Orange
    error: "#EF4444"              # Kräftiges Rot

# Protokollierungseinstellungen
logging:
  level: "info"  # Protokollierungsebene (debug, info, warning, error)
  file_logging: true  # In Datei protokollieren
  console_logging: true  # In Konsole protokollieren
  max_log_files: 10  # Maximale Anzahl von Protokolldateien
  max_file_size_mb: 5  # Maximale Größe der Protokolldatei in MB

# Automatisierungseinstellungen
automation:
  auto_process_new_files: false  # Automatisch neue Dateien verarbeiten
  polling_interval_seconds: 300  # Intervall für die Überprüfung auf neue Dateien (5 Minuten)
  notifications_enabled: true  # Benachrichtigungen bei automatischer Verarbeitung aktivieren
  schedule:
    enabled: false  # Zeitplanbasierte Verarbeitung aktivieren
    time: "18:00"  # Tägliche Verarbeitungszeit (24-Stunden-Format)
    days: [1, 2, 3, 4, 5]  # Wochentage (1 = Montag, 7 = Sonntag)

# Erweiterte Einstellungen
advanced:
  debug_mode: false  # Debug-Modus aktivieren
  keep_original_files: false  # Originaldateien nicht mehr behalten, da wir sie jetzt markieren und verschieben
  mark_processed_files: true  # Neue Option: Verarbeitete Dateien markieren und verschieben
  temp_directory: ""  # Temporäres Verzeichnis (leer = Systemstandard)
  memory_limit_mb: 512  # Speicherlimit in MB für die Verarbeitung großer Dateien
  timeout_seconds: 60  # Zeitlimit für die Verarbeitung einer einzelnen Datei
  max_concurrent_files: 1  # Maximale Anzahl gleichzeitig zu verarbeitender Dateien
